gateway: true
logging_enabled: false
logging_level: "WARN"
source_dir: build
disable_password_login: false
remote_mesh_access: false
insert_keys: false
keys_to_insert:
  - ""
dropbear_wan_accessible: false
ssh_port: 22
password_auth: 0
default_price: 100
wireless_conf_path: "{{role_path}}/templates/{{conf_to_build}}-wireless.j2"

# literally everything
mesh_subnets:
  - "8000::/1"
  - "0000::/1"

wifi_key: "ChangeMe"

lan_ip: "192.168.10.1"

stats_enabled: false
stats_server: "nope.nope"
wifi_encryption: psk2+tkip+aes
