---
# Builds the more sensitive and dynamic parts of the firmware root configuration
# for example ssh keys are inserted in this role

- name: Create Dropbear folder
  file:
    path: "{{source_dir}}/files/etc/dropbear/"
    state: directory

- name: Add keys to login
  lineinfile:
    dest: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    line: "{{item}}"
    state: present
    create: yes
  with_items: "{{keys_to_insert}}"

- name: Authorized keys only readable by owner
  file:
    path: "{{source_dir}}/files/etc/dropbear/authorized_keys"
    mode: 0600

- name: Template dropbear config
  template:
    src: "dropbear.j2"
    dest: "{{source_dir}}/files/etc/config/dropbear"


- name: Create Wireguard Config folder
  file:
    path: "{{source_dir}}/files/etc/config/"
    state: directory

# Network and wifi stuff is hardware specific, so we keep templates for each
# supported device. it really shouldn't ever change much
# but do remember it's possible
- name: Template network interface configuration
  template:
    src: "{{conf_to_build}}-network.j2"
    dest: "{{source_dir}}/files/etc/config/network"

- name: Template wifi interface configuration
  template:
    src: "{{conf_to_build}}-wireless.j2"
    dest: "{{source_dir}}/files/etc/config/wireless"

- name: Add wireguard interface to network configuration
  lineinfile:
    dest: "{{source_dir}}/files/etc/config/network"
    line: "config interface 'wg0' \n\
             \t option proto 'wireguard' \n\
             \t option private_key '{{wg_private_key}}' \n\
             \t list addresses '10.0.0.0/8'\n"
    state: present

- name: Add exit server peer to network configuration
  lineinfile:
    dest: "{{source_dir}}/files/etc/config/network"
    line: "config wireguard_wg0 \n\
             \t option public_key '{{wg_server_public_key}}' \n\
             \t option preshared_key '{{wg_server_preshared_key}}' \n\
             \t option route_allowed_ips '1' \n\
             \t list allowed_ips '10.0.0.0/8' \n\
             \t option endpoint_host '{{wg_server}}' \n\
             \t option endpoint_port '{{wg_port}}'\n"
    state: present

- name: Generate Babeld interface configuration from hardware configuration
  lineinfile:
    dest: "{{source_dir}}/files/etc/config/babeld"
    line: "{{item}}"
    state: present
  with_items: "{{babeld_interfaces}}"

- name: Write out build details
  template:
    src: "althea-firmware-release.j2"
    dest: "{{source_dir}}/files/etc/althea-firmware-release"
